# -*- coding: utf-8 -*-
"""WeatherDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A96zQQ840hpOKjpvWnWqG4RmWFbhQ6ja
"""

import pandas as pd

df = pd.read_csv('WeatherData.csv')

df.head()

df.tail()

df.shape

df.index

df.columns

df.dtypes

"""#### Q1. Find all the Unique 'Weather' values in the data set."""

df['Weather'].unique()   #onlu on particular column it works not on whole dataframe

df.nunique()

"""#### Q2. Find the number of unique values in each column."""

df.count()

df.value_counts

df.info()

df.groupby('Weather').get_group('Clear')

df[df['Weather'] == 'Clear']

df.head(2)

"""#### Q9. Find all the records where 'Wind Speed is exactly 4 km/h."""

df[df['Wind Speed_km/h'] == 4]



"""#### Q3. Find the number of null values and non null values in each column."""

df.isnull().sum()

df.notnull().sum()

"""#### Q4. Rename the column name 'Weather' to 'Weather Condition'."""

df.rename(columns = {'Weather' : 'Weather Condition'}, inplace = True)
df

"""#### Q5. What is the Mean 'Visibility'?"""

df.Visibility_km.mean()

"""#### Q6. What is the Standard Deviation of 'Pressure'?"""

df.Press_kPa.std()

"""#### Q7. What is the Variance of humidity?"""

df['Rel Hum_%'].var()

df['Weather Condition'].value_counts()

"""#### Q8. Find all instances when 'Snow' was recorded."""

df['Weather Condition'] == 'Snow'

df[df['Weather Condition'].str.contains('Snow')].tail(50)

(df['Wind Speed_km/h'] > 24) & (df['Wind Speed_km/h'] == 25 )

"""#### Q10. Find the Mean of each column against each 'Weather Condition'."""

df.groupby('Weather Condition').mean(numeric_only=True)

"""#### Q11. Find the Minimum value of each column against each 'Weather Condition'."""

df.groupby('Weather Condition').min(numeric_only=True)

"""#### Q12. Find the Maximum value of each column against each 'Weather Condition'."""

df.groupby('Weather Condition').max(numeric_only=True)

"""#### Q13. Show all the records where 'Weather Condition' is 'Fog'."""

df[df['Weather Condition'] == 'Fog']

"""#### Q14. Find all instances when 'Weather Condition' is 'Clear' and 'Visibility_km' is greater than 40."""

df[(df['Weather Condition'] == 'Clear') & (df['Visibility_km'] > 40)]

"""#### Q15. Find all instances when 'Weather Condition' is 'Clear' and 'Rel Hum_%' is greater than 50 or 'Visibility_km' is greater than 40."""

df[(df['Weather Condition'] == 'Clear') & (df['Rel Hum_%'] > 50) | (df['Visibility_km'] > 40)]

"""#### Q11. Find the Minimum value of each column against each 'Weather Condition'.

#### Q12. Find the Maximum value of each column against each 'Weather Condition'.

#### Q13. Show all the records where 'Weather Condition' is 'Fog'.

#### Q14. Find all instances when 'Weather Condition' is 'Clear' and 'Visibility_km' is greater than 40.
"""